### PR TITLE
IMGUI Update, ICONS and UI Restyle

### PR DESCRIPTION
**Pull request by honzapatCZ**
Added Roboto and ForkAwesome
Updated IMGUI to latest version
Chaged styles and colors so now it looks like this
image

### CODE REVIEW

**Review by honzapatCZ — COMMENTED** [review]
Indentation missing, So I added 12, so it matches other stuff

**Comment by honzapatCZ** [comment]
@deadcast2 Sorry for ping, but what you think? I have few other ideas, like saving layout(almost done), moving some menus etc. Could you review this PR and merge it?

**Comment by deadcast2** [comment]
@honzapatCZ Hey! Sorry for the long delay. I've been busy moving to a new house and my internet is still not working yet. Was supposed to be fixed today but the fiber optics were installed wrong... ugh. I'm commenting via my phone currently so hopefully soon I'll have some time to look through the changes.

Before my move I was really busy working on the asset tracking system in the other branch and it has some other nice changes like texture/model previewing, project saving/loading and auto updating of assets when changed outside the editor. Will eventually get back to that branch and get is finished so it can eventually be merged into master. Just a little update on what I'm currently doing. :)

**Comment by honzapatCZ** [comment]
@deadcast2 Iam working with the asset tracking branch, dont worry, the PR is also against your asset tracking branch, both of them

**Pull request merged**
